[package]
name = "sel4_cspace_proofs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]
name = "sel4_cspace_proofs"
path = "src/lib.rs"

[features]
verus = []
verify = ["verus"]
alloc = []
default = ["verify", "alloc"]

[package.metadata.verus]
path = "src/lib.rs"
verify = true

[dependencies]
sel4_cspace_specs = { path = "../../specs/sel4_cspace" }
